version: "3.9"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  backend:
    build: .
    command: uvicorn main:app --reload
    restart: always
    volumes:
      - .:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data:
