version: "3.9"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
  test_db:
    container_name: "test_db"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql_test/data
    env_file:
      - ./app/.env
    ports:
      - "6000:5432"
#  pgadmin:
#    container_name: "pgadmin"
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
  backend:
    container_name: "backend"
    build: app
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
    restart: always
    volumes:
      - ./app:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db
volumes:
  postgres_data:
