"""empty message

Revision ID: 93c97f728cf7
Revises: 002f3b8ea2e3
Create Date: 2024-01-07 12:38:35.341824

"""
import sqlalchemy as sa
from sqlalchemy import orm, select, table

from alembic import op
from users.models import User

# revision identifiers, used by Alembic.
revision = "93c97f728cf7"
down_revision = "002f3b8ea2e3"
branch_labels = None
depends_on = None


def update_phone_numbers():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    users = session.scalars(select(User)).all()
    for index, user in enumerate(users):
        user.phone_number = f"+37529000000{str(index)}"
    session.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    update_phone_numbers()
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "user", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
