"""empty message

Revision ID: bb9389407725
Revises: ed50e1e5022b
Create Date: 2024-03-10 16:07:59.937735

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bb9389407725"
down_revision = "ed50e1e5022b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_code",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promo_code_id"), "promo_code", ["id"], unique=True)
    op.create_table(
        "product_variant",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False, comment="Price in kopecks"),
        sa.Column("discount", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "weight", name="idx_unique_product_weight"),
    )
    op.create_index(op.f("ix_product_variant_id"), "product_variant", ["id"], unique=False)
    op.create_table(
        "basket_product",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_variant_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["product_variant_id"], ["product_variant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_variant_id", name="idx_unique_user_basket_product"),
    )
    op.create_index(op.f("ix_basket_product_id"), "basket_product", ["id"], unique=False)
    op.create_table(
        "promo_product_association",
        sa.Column("promo_code_id", sa.String(), nullable=False),
        sa.Column("product_variant_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["product_variant_id"], ["product_variant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["promo_code_id"], ["promo_code.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("promo_code_id", "product_variant_id", name="idx_unique_promo_product"),
    )
    op.create_index(op.f("ix_promo_product_association_id"), "promo_product_association", ["id"], unique=False)
    op.drop_column("product", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_promo_product_association_id"), table_name="promo_product_association")
    op.drop_table("promo_product_association")
    op.drop_index(op.f("ix_basket_product_id"), table_name="basket_product")
    op.drop_table("basket_product")
    op.drop_index(op.f("ix_product_variant_id"), table_name="product_variant")
    op.drop_table("product_variant")
    op.drop_index(op.f("ix_promo_code_id"), table_name="promo_code")
    op.drop_table("promo_code")
    # ### end Alembic commands ###
