"""empty message

Revision ID: 7cdf03566eee
Revises: 337110d18478
Create Date: 2023-07-30 17:32:06.506741

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7cdf03566eee"
down_revision = "337110d18478"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
