"""empty message

Revision ID: 8c44b35b51dc
Revises: 002f3b8ea2e3
Create Date: 2023-12-16 15:54:44.067913

"""
import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = '8c44b35b51dc'
down_revision = '002f3b8ea2e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
