"""empty message

Revision ID: a8de538ec3fc
Revises: e4cd5ab3923a
Create Date: 2023-08-16 10:27:14.691740

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8de538ec3fc"
down_revision = "e4cd5ab3923a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_price_key", "product", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("product_price_key", "product", ["price"])
    # ### end Alembic commands ###
